### ISSUE TITLE
Would it be hard to make an SVG version?

### ISSUE THREAD

**Issue by davidaramant** [benjamin-hodgson/Eighty#2]
I want to programmatically create some SVG files that will get written straight to disk; no web server involved.  Every SVG framework I've found seems pretty cumbersome to use, especially since I don't care about rendering them.

Would supporting SVG just be a matter of updating the generators for some different tag names, or am I missing something?  Theoretically the HTML & SVG models could even be combined somehow since you can embed HTML inside of SVG (and vice versa, obviously), although there are XML namespace issues to deal with.  

My end goal is to have the SVG file be a stand-alone visualizer "application" with embedded HTML/JS.  People normally embed the two the other way around, but I've done something like this for work as debug output for a C++ app and having it self-contained as a single file was very useful.  I wanted to play with SVGs some more for fun too using a free domain and a language I didn't hate and this project might save me some time 🙂.

**Comment by benjamin-hodgson** [comment]
I don't think it would be hard! Most of the API is generated by a script, so in theory you should be able to update the script and get a build of the library with a different set of tags and attributes.

1. Fork this project
2. Update the list of tags and attributes in [`EightyCodeGenerator`](https://github.com/benjamin-hodgson/Eighty/blob/master/Eighty.CodeGen/EightyCodeGenerator.cs) to correspond to SVG's tags and attributes.
3. Run that project (`dotnet run --project Eighty.CodeGen`)
4. It should spit out several C# files into [the `Eighty` folder](https://github.com/benjamin-hodgson/Eighty/tree/master/Eighty). It sounds like you can probably get away with just pasting the whole folder into your own project, but if you wanted to repackage it as a library that's 100% fine with me! (You'd need to do some renaming of course.)

**Comment by benjamin-hodgson** [comment]
Regarding combining HTML and SVG - that might require a bit more thought about the API. I'd have to think about whether HTML and SVG need to be separate types.

**Comment by davidaramant** [comment]
Do you think it makes sense to add SVG as part of this project, or would you want it to be a completely separate thing?  I'm far from an SVG expert and probably don't have much sustainable motivation to work on something like that long-term, but I can certainly help out a bit.  

SVG has some different concepts from HTML like restricting the valid children of certain elements so making a bullet-proof generator might require a fair amount of work.  On the other hand, an 80% "good enough" generator might still be useful.  It looks like Twenty already takes a similar philosophy in that it won't guarantee that the output is valid if you don't use it right.  I can totally understand if you have no interest in including half-baked SVG support though, especially since it will probably be extremely rare that anyone uses it 🙂
